@EndUserText.label: 'Approve Request Medical'

@VDM.viewType: #CONSUMPTION
@VDM.usage.type:[#TRANSACTIONAL_PROCESSING_SERVICE]
@ObjectModel.usageType:{
  serviceQuality: #X,
  sizeCategory: #S,
  dataClass: #MIXED
}
@ObjectModel.query.implementedBy: 'ABAP:ZCL_HCM_SOLIC_DESCANSO_MEDICO'
define root custom entity ZC_HCM_APPROVE_REQUEST_MED

{
      @UI.dataFieldDefault: [ { label: 'Matricula' } ]
      @UI.selectionField: [ { position: 10 } ]
            @UI.lineItem: [ { position: 10 } ]
  key RequestID         : zesoldes;
      @UI.lineItem: [ { position: 20 } ]
  key CompanyCode : bukrs;

      EmployeeNumber    : pernr_d;

      @UI.dataFieldDefault: [ { label: 'Matricula' } ]
      @UI.selectionField: [ { position: 20 } ]
      UsrID9000         : sysid;

      @UI.dataFieldDefault: [ { label: 'Nombre y Apellidos' } ]
      @UI.selectionField: [ { position: 30 } ]
      EmployeeName      : emnam;

      @UI.dataFieldDefault: [ { label: 'Código Autogenerado' } ]
      @UI.selectionField: [ { position: 40 } ]
      AutogeneratedCode : zeautogen;


      @UI.dataFieldDefault: [ { label: 'Centro Médico' } ]
      @UI.selectionField: [ { position: 50 } ]
      MCDescription     : zecmdescr;

      @UI.dataFieldDefault: [ { label: 'Fecha de Emisión' } ]
      @UI.selectionField: [ { position: 60 } ]
      IssueDate         : zsoldes_emision;

      @UI.dataFieldDefault: [ { label: 'Fecha de Inicio del DM' } ]
      @UI.selectionField: [ { position: 70 } ]
      DateStartMC       : begda;

      @UI.dataFieldDefault: [ { label: 'Fecha de Término del DM' } ]
      @UI.selectionField: [ { position: 80 } ]
      DateEndMC         : endda;

      @UI.dataFieldDefault: [ { label: 'Tipo de Enfermedad' } ]
      @UI.selectionField: [ { position: 90 } ]
      TDisDesc          : zetdescr;

      @UI.dataFieldDefault: [ { label: 'Clasificación' } ]
      @UI.selectionField: [ { position: 100 } ]
      ClassifDesc1       : zecdescr;

      @UI.dataFieldDefault: [ { label: 'Especificación' } ]
      @UI.selectionField: [ { position: 110 } ]
      EspecDesc1       : zeedescr;

      @UI.dataFieldDefault: [ { label: 'Otros' } ]
      @UI.selectionField: [ { position: 120 } ]
      Others1             : zeotros;

      @UI.dataFieldDefault: [ { label: 'Clasificación' } ]
      @UI.selectionField: [ { position: 130 } ]
      ClassifDesc2       : zecdescr;

      @UI.dataFieldDefault: [ { label: 'Especificación' } ]
      @UI.selectionField: [ { position: 140 } ]
      EspecDesc2       : zeedescr;

      @UI.dataFieldDefault: [ { label: 'Otros' } ]
      @UI.selectionField: [ { position: 150 } ]
      Others2             : zeotros;

      @UI.dataFieldDefault: [ { label: 'Clasificación' } ]
      @UI.selectionField: [ { position: 160 } ]
      ClassifDesc3       : zecdescr;

      @UI.dataFieldDefault: [ { label: 'Especificación' } ]
      @UI.selectionField: [ { position: 170 } ]
      EspecDesc3       : zeedescr;

      @UI.dataFieldDefault: [ { label: 'Otros' } ]
      @UI.selectionField: [ { position: 180 } ]
      Others3             : zeotros;

      @UI.dataFieldDefault: [ { label: 'Observación' } ]
      @UI.selectionField: [ { position: 190 } ]
      ReasonRejection     : zeobservacion;

      @UI.dataFieldDefault: [ { label: 'Estado Aprobación' } ]
      @UI.selectionField: [ { position: 200 } ]
      Flag               : flag;

      FilePath          : zesoldes_ruta;
      FileType          : abap.string;

      @UI.dataFieldDefault: [ { label: 'Archivo' } ]
      @UI.selectionField: [ { position: 210 } ]
      FileBin        : zesoldes_bin;
}
