@EndUserText.label: 'Request medical employee'

@ObjectModel.query.implementedBy: 'ABAP:ZCL_HCM_SOLIC_DESCANSO_MEDICO'
define root custom entity ZC_HCM_REQUEST_MED_EMPLOYEE

{
      @UI.selectionField: [ { position: 10 } ]
  key EmployeeNumber    : pernr_d;

      @UI.selectionField: [ { position: 20 } ]
      EmployeeName      : emnam;

      UserID            : sysid;

      @UI.selectionField: [ { position: 30 } ]
      RequestID         : zesoldes;

      Correlative       : zesoldes;

      @UI.selectionField: [ { position: 40 } ]
      AutogeneratedCode : zeautogen;

      @UI.selectionField: [ { position: 50 } ]
      MCCode            : zecmcodigo;

      MCDescription     : zecmdescr;

      @UI.selectionField: [ { position: 60 } ]
      IssueDate         : zsoldes_emision;

      @UI.selectionField: [ { position: 70 } ]
      DateStartMC       : begda;

      @UI.selectionField: [ { position: 80 } ]
      DateEndMC         : endda;

      @UI.selectionField: [ { position: 90 } ]
      TDisCode          : zetcodig;

//      TDisDesc          : zetdescr;
      ClassifCode1      : zeccodig;
//      ClassifDesc1      : zecdescr;
      EspecCode1        : zeecodig;
//      EspecDesc1        : zeedescr;
      Others1           : zeotros;
      ClassifCode2      : zeccodig;
//      ClassifDesc2      : zecdescr;
      EspecCode2        : zeecodig;
//      EspecDesc2        : zeedescr;
      Others2           : zeotros;
      ClassifCode3      : zeccodig;
//      ClassifDesc3      : zecdescr;
      EspecCode3        : zeecodig;
//      EspecDesc3        : zeedescr;
      Others3           : zeotros;
      FilePath          : zesoldes_ruta;
      FileBin           : zesoldes_bin;
      FileType          : abap.string;

      UsrID9000         : sysid;
//      @Consumption.hidden: true
//      MessageText       : bapi_msg;
////      @Consumption.hidden: true
//      MessageID         : char1;  
}
