@AbapCatalog.viewEnhancementCategory: [ #NONE ]

@AccessControl.authorizationCheck: #NOT_REQUIRED

@EndUserText.label: 'Calendar Employee'

@Metadata.ignorePropagatedAnnotations: true

@ObjectModel.representativeKey: 'RequestID'
@ObjectModel.usageType: { serviceQuality: #X, sizeCategory: #S, dataClass: #MIXED }


define root view entity ZI_HCM_APPROVE_REQUEST_EMPL
  as select from zthr_soldesmedic

{
  key bukrs                                                                   as CompanyCode, --Codigo de Compañia
        @UI.dataFieldDefault: [ { label: 'Solicitud' } ]
      @UI.lineItem: [ { position: 10 } ]
  key soldes                                                                  as  RequestID, --Número de Solicitud

      @UI.dataFieldDefault: [ { label: 'Matricula' } ]
      @UI.selectionField: [ { position: 10 } ]
      usrid_9000                                                              as  UsrID9000, --Matricula


//      autogenerado                                                            as  AutogeneratedCode,

      @UI.dataFieldDefault: [ { label: 'Descripcción' } ]
      @UI.lineItem: [ { position: 30 } ]
      cast(concat(usrid_9000, concat('-', empleado_nombre)) as abap.char(80)) as Description, -- Nombre Empleado

      @UI.dataFieldDefault: [ { label: 'Fecha de Registro' } ]
      @UI.lineItem: [ { position: 30 } ]
      idate                                                                   as  IssueDate
//      estado_solicitud                                                        as  RequestStatus,
//      empleado_solicitud                                                      as  EmployeeNumber,
//      empleado_nombre                                                         as  EmployeeName,
//
//      usuario_solicitud                                                       as  UserID,



//      cm_codigo                                                               as  MCCode,
//      cm_descr                                                                as  MCDescription,
//
//      begda                                                                   as  DateStartMC,
//      endda                                                                   as  DateEndMC,
//      tenf_code                                                               as  TDisCode,
//      tenf_desc                                                               as  TDisDesc,
//      clasfi_code1                                                            as  ClassifCode1,
//      calsfi_desc1                                                            as  ClassifDesc1,
//      especi_code1                                                            as  EspecCode1,
//      especi_desc1                                                            as  EspecDesc1,
//      otros1                                                                  as  Others1,
//      clasfi_code2                                                            as  ClassifCode2,
//      calsfi_desc2                                                            as  ClassifDesc2,
//      especi_code2                                                            as  EspecCode2,
//      especi_desc2                                                            as  EspecDesc2,
//      otros2                                                                  as  Others2,
//      clasfi_code3                                                            as  ClassifCode3,
//      calsfi_desc3                                                            as  ClassifDesc3,
//      especi_code3                                                            as  EspecCode3,
//      especi_desc3                                                            as  EspecDesc3,
//      otros3                                                                  as  Others3,
//      archivo                                                                 as  FilePath,
//      tipo_archivo                                                            as  FileType,
//      archivo_bin                                                             as  FileBin
}

where estado_solicitud = 'P'
