@AbapCatalog.viewEnhancementCategory: [#NONE]
@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'HCM Basic Pay'
@Metadata.ignorePropagatedAnnotations: true
@ObjectModel.usageType:{
    serviceQuality: #X,
    sizeCategory: #S,
    dataClass: #MIXED
}
define view entity ZI_HCMBasicPay  as select from pa0008
  association [0..1] to t510a as _tr10a on $projection.PayScaleType = _tr10a.trfar and
                                            _tr10a.molga = '99'
  association [0..1] to t510g as _tr10g on $projection.PayScaleArea = _tr10g.trfgb and
                                                 _tr10g.molga = '99'
  association [0..1] to I_Currency as _Currency on $projection.Currency = _Currency.Currency
//  association [0..1] to ZI_HCM_PayGradeLevels as _PayGradeLevels on $projection.
association [0..1] to ZI_HCM_PayGradeLevels as _PayGradeLevels on $projection.PayScaleType = _PayGradeLevels.Sltyp and
                                                               $projection.PayScaleArea = _PayGradeLevels.Slreg and     
                                                               $projection.PayScaleGroup = _PayGradeLevels.Slgrp and     
                                                               $projection.PayScaleLevel = _PayGradeLevels.Sllvl    
                                                                 
                                                                    
{
      // HR Master Record: Key Fields
  key pernr     as HCMPersonnelNumber,
  key subty     as HCMSubtype,
  key objps     as HCMObjectIdentification,
      @Semantics.booleanIndicator: true
  key sprps     as HCMRecordIsLocked,
      @Semantics.businessDate.to: true
  key endda     as EndDate,
      @Semantics.businessDate.from: true
  key begda     as StartDate,
  key seqnr     as HCMSequentialNumber,

      // HR Master Record: Control Fields
//      aedtm as LastChangedDate,
//      uname as LastChangedByUser,
//      @Semantics.booleanIndicator:true
//      histo     as HCMInfoTypeRecordIsHistorical,
//      itxex     as HCMInfoTypeRecordHasText,
//      refex     as HCMInfoTypeRecordHasRefField,
//      ordex     as HCMInfoTypeRecordHasConfField,
//      itbld     as HCMInfoTypeRecordScreenCtrl, //
//      preas     as HCMMasterDataChangeReason, // association needed
//      flag1     as HCMInfoTypeRecordRsrvdFld1,
//      flag2     as HCMInfoTypeRecordRsrvdFld2,
//      flag3     as HCMInfoTypeRecordRsrvdFld3,
//      flag4     as HCMInfoTypeRecordRsrvdFld4,
//      rese1     as HCMInfoTypeRecordRsrvdFld1Len2,
//      rese2     as HCMInfoTypeRecordRsrvdFld2Len2,
//      grpvl     as HCMGrpgValForPersAssignments,

      // HR Master Record: Infotype 0008 (Basic Pay)
      @ObjectModel.text.element: [ 'PayScaleTypeText' ]
      trfar as PayScaleType,
      
      @ObjectModel.text.element: [ 'PayScaleAreaText' ]
      trfgb as PayScaleArea,
      trfgr as PayScaleGroup,
      trfst as PayScaleLevel,/*
      stvor as NextIncreaseDate,
      orzst as CostOfLivingAllowanceLevel,
      partn as Partnership,*/
      @ObjectModel.foreignKey.association: '_Currency'
      waers as Currency,
       bsgrd as CapacityUtilizationLevel,
      @Semantics.amount.currencyCode: 'Currency'
     case '0440'
      when lga01 then bet01
      when lga02 then bet02
      when lga03 then bet03
      when lga04 then bet04
      when lga05 then bet05
      when lga06 then bet06
      when lga07 then bet07 
      when lga08 then bet08
      when lga09 then bet09
      else bet10
      end as Salary,
      @Semantics.text: true
      _tr10a.tartx as PayScaleTypeText,
     @Semantics.text: true
      _tr10g.tgbtx as PayScaleAreaText,
         
      
      /*
      vglta as ComparisonPayScaleType,
      vglgb as ComparisonPayScaleArea,
      vglgr as ComparisonPayScaleGroup,
      vglst as ComparisonPayScaleLevel,
      vglsv as ComparisonNextIncreaseDate,
      bsgrd as CapacityUtilizationLevel,
      divgv as WorkingHoursPerPayrollPeriod,
      ansal as AnnualSalary,
      falgk as CaseGroupCatalog,
      falgr as CaseGroup,
      lga01 as WageType01,
      bet01 as WageTypeAmountForPayments01,
      anz01 as Number01,
      ein01 as TimeUoM01,
      opk01 as OperationForWageTypes01,
      lga02 as WageType02,
      bet02 as WageTypeAmountForPayments02,
      anz02 as Number02,
      ein02 as TimeUoM02,
      opk02 as OperationForWageTypes02,
      lga03 as WageType03,
      bet03 as WageTypeAmountForPayments03,
      anz03 as Number03,
      ein03 as TimeUoM03,
      opk03 as OperationForWageTypes03,
      lga04 as WageType04,
      bet04 as WageTypeAmountForPayments04,
      anz04 as Number04,
      ein04 as TimeUoM04,
      opk04 as OperationForWageTypes04,
      lga05 as WageType05,
      bet05 as WageTypeAmountForPayments05,
      anz05 as Number05,
      ein05 as TimeUoM05,
      opk05 as OperationForWageTypes05,
      lga06 as WageType06,
      bet06 as WageTypeAmountForPayments06,
      anz06 as Number06,
      ein06 as TimeUoM06,
      opk06 as OperationForWageTypes06,
      lga07 as WageType07,
      bet07 as WageTypeAmountForPayments07,
      anz07 as Number07,
      ein07 as TimeUoM07,
      opk07 as OperationForWageTypes07,
      lga08 as WageType08,
      bet08 as WageTypeAmountForPayments08,
      anz08 as Number08,
      ein08 as TimeUoM08,
      opk08 as OperationForWageTypes08,
      lga09 as WageType09,
      bet09 as WageTypeAmountForPayments09,
      anz09 as Number09,
      ein09 as TimeUoM09,
      opk09 as OperationForWageTypes09,
      lga10 as WageType10,
      bet10 as WageTypeAmountForPayments10,
      anz10 as Number10,
      ein10 as TimeUoM10,
      opk10 as OperationForWageTypes10,
      lga11 as WageType11,
      bet11 as WageTypeAmountForPayments11,
      anz11 as Number11,
      ein11 as TimeUoM11,
      opk11 as OperationForWageTypes11,
      lga12 as WageType12,
      bet12 as WageTypeAmountForPayments12,
      anz12 as Number12,
      ein12 as TimeUoM12,
      opk12 as OperationForWageTypes12,
      lga13 as WageType13,
      bet13 as WageTypeAmountForPayments13,
      anz13 as Number13,
      ein13 as TimeUoM13,
      opk13 as OperationForWageTypes13,
      lga14 as WageType14,
      bet14 as WageTypeAmountForPayments14,
      anz14 as Number14,
      ein14 as TimeUoM14,
      opk14 as OperationForWageTypes14,
      lga15 as WageType15,
      bet15 as WageTypeAmountForPayments15,
      anz15 as Number15,
      ein15 as TimeUoM15,
      opk15 as OperationForWageTypes15,
      lga16 as WageType16,
      bet16 as WageTypeAmountForPayments16,
      anz16 as Number16,
      ein16 as TimeUoM16,
      opk16 as OperationForWageTypes16,
      lga17 as WageType17,
      bet17 as WageTypeAmountForPayments17,
      anz17 as Number17,
      ein17 as TimeUoM17,
      opk17 as OperationForWageTypes17,
      lga18 as WageType18,
      bet18 as WageTypeAmountForPayments18,
      anz18 as Number18,
      ein18 as TimeUoM18,
      opk18 as OperationForWageTypes18,
      lga19 as WageType19,
      bet19 as WageTypeAmountForPayments19,
      anz19 as Number19,
      ein19 as TimeUoM19,
      opk19 as OperationForWageTypes19,
      lga20 as WageType20,
      bet20 as WageTypeAmountForPayments20,
      anz20 as Number20,
      ein20 as TimeUoM20,
      opk20 as OperationForWageTypes20,
      lga21 as WageType21,
      bet21 as WageTypeAmountForPayments21,
      anz21 as Number21,
      ein21 as TimeUoM21,
      opk21 as OperationForWageTypes21,
      lga22 as WageType22,
      bet22 as WageTypeAmountForPayments22,
      anz22 as Number22,
      ein22 as TimeUoM22,
      opk22 as OperationForWageTypes22,
      lga23 as WageType23,
      bet23 as WageTypeAmountForPayments23,
      anz23 as Number23,
      ein23 as TimeUoM23,
      opk23 as OperationForWageTypes23,
      lga24 as WageType24,
      bet24 as WageTypeAmountForPayments24,
      anz24 as Number24,
      ein24 as TimeUoM24,
      opk24 as OperationForWageTypes24,
      lga25 as WageType25,
      bet25 as WageTypeAmountForPayments25,
      anz25 as Number25,
      ein25 as TimeUoM25,
      opk25 as OperationForWageTypes25,
      lga26 as WageType26,
      bet26 as WageTypeAmountForPayments26,
      anz26 as Number26,
      ein26 as TimeUoM26,
      opk26 as OperationForWageTypes26,
      lga27 as WageType27,
      bet27 as WageTypeAmountForPayments27,
      anz27 as Number27,
      ein27 as TimeUoM27,
      opk27 as OperationForWageTypes27,
      lga28 as WageType28,
      bet28 as WageTypeAmountForPayments28,
      anz28 as Number28,
      ein28 as TimeUoM28,
      opk28 as OperationForWageTypes28,
      lga29 as WageType29,
      bet29 as WageTypeAmountForPayments29,
      anz29 as Number29,
      ein29 as TimeUoM29,
      opk29 as OperationForWageTypes29,
      lga30 as WageType30,
      bet30 as WageTypeAmountForPayments30,
      anz30 as Number30,
      ein30 as TimeUoM30,
      opk30 as OperationForWageTypes30,
      lga31 as WageType31,
      bet31 as WageTypeAmountForPayments31,
      anz31 as Number31,
      ein31 as TimeUoM31,
      opk31 as OperationForWageTypes31,
      lga32 as WageType32,
      bet32 as WageTypeAmountForPayments32,
      anz32 as Number32,
      ein32 as TimeUoM32,
      opk32 as OperationForWageTypes32,
      lga33 as WageType33,
      bet33 as WageTypeAmountForPayments33,
      anz33 as Number33,
      ein33 as TimeUoM33,
      opk33 as OperationForWageTypes33,
      lga34 as WageType34,
      bet34 as WageTypeAmountForPayments34,
      anz34 as Number34,
      ein34 as TimeUoM34,
      opk34 as OperationForWageTypes34,
      lga35 as WageType35,
      bet35 as WageTypeAmountForPayments35,
      anz35 as Number35,
      ein35 as TimeUoM35,
      opk35 as OperationForWageTypes35,
      lga36 as WageType36,
      bet36 as WageTypeAmountForPayments36,
      anz36 as Number36,
      ein36 as TimeUoM36,
      opk36 as OperationForWageTypes36,
      lga37 as WageType37,
      bet37 as WageTypeAmountForPayments37,
      anz37 as Number37,
      ein37 as TimeUoM37,
      opk37 as OperationForWageTypes37,
      lga38 as WageType38,
      bet38 as WageTypeAmountForPayments38,
      anz38 as Number38,
      ein38 as TimeUoM38,
      opk38 as OperationForWageTypes38,
      lga39 as WageType39,
      bet39 as WageTypeAmountForPayments39,
      anz39 as Number39,
      ein39 as TimeUoM39,
      opk39 as OperationForWageTypes39,
      lga40 as WageType40,
      bet40 as WageTypeAmountForPayments40,
      anz40 as Number40,
      ein40 as TimeUoM40,
      opk40 as OperationForWageTypes40,
      ind01 as IsIndirectValuation01,
      ind02 as IsIndirectValuation02,
      ind03 as IsIndirectValuation03,
      ind04 as IsIndirectValuation04,
      ind05 as IsIndirectValuation05,
      ind06 as IsIndirectValuation06,
      ind07 as IsIndirectValuation07,
      ind08 as IsIndirectValuation08,
      ind09 as IsIndirectValuation09,
      ind10 as IsIndirectValuation10,
      ind11 as IsIndirectValuation11,
      ind12 as IsIndirectValuation12,
      ind13 as IsIndirectValuation13,
      ind14 as IsIndirectValuation14,
      ind15 as IsIndirectValuation15,
      ind16 as IsIndirectValuation16,
      ind17 as IsIndirectValuation17,
      ind18 as IsIndirectValuation18,
      ind19 as IsIndirectValuation19,
      ind20 as IsIndirectValuation20,
      ind21 as IsIndirectValuation21,
      ind22 as IsIndirectValuation22,
      ind23 as IsIndirectValuation23,
      ind24 as IsIndirectValuation24,
      ind25 as IsIndirectValuation25,
      ind26 as IsIndirectValuation26,
      ind27 as IsIndirectValuation27,
      ind28 as IsIndirectValuation28,
      ind29 as IsIndirectValuation29,
      ind30 as IsIndirectValuation30,
      ind31 as IsIndirectValuation31,
      ind32 as IsIndirectValuation32,
      ind33 as IsIndirectValuation33,
      ind34 as IsIndirectValuation34,
      ind35 as IsIndirectValuation35,
      ind36 as IsIndirectValuation36,
      ind37 as IsIndirectValuation37,
      ind38 as IsIndirectValuation38,
      ind39 as IsIndirectValuation39,
      ind40 as IsIndirectValuation40,
      ancur as AnnualSalaryCurrency,
      cpind as PlannedCompensationType,
      flaga as GeneralFlag,*/

      //Associations
      _PayGradeLevels,
      _Currency
}
